#注册
registerWithEureka: false
#是否从eureka服务器获取注册信息
fetchRegistry: false
#端口
server:
  port: 5655
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/